travis:
  secure:
    BINSTAR_TOKEN: qZ3BQMP0KDS05kwdsmy3FKHW0EAIgBiy0BAGchO37jix+GUTaZr/1mX69UZImpi+XVrchiotEEZQH0NYEsTqpvdT2ZeXs2XYAdpo/qJakWAGXYaLpLcX/uidOqGY+ZHt4bkj/bCyWMSzP6pxjmQXyplHBi995I3sspYwxJFqpM9DcxK+3farHxPYy3jMzK6w+8eEDtsdsEzNznaDNa9h5N1NT3vmSnaHFssj6HB2Q0LbKbyppMTG5wiLUOV017gOqf+GP2edN91sEgDG948lbPv91Ip8T8SoBwVP6tPM/DlYW+CNmL+Eij6L/ATQhW65XBdJNKve/I6B74EA985WF3Een8z29dQvP2NQV0KcMdWQTnF0+V/Ovj0+q96SWRjY4dgCUnKRcHnamVM6NGGdWGt1AE86D5eO+vj1OoIYFCGcnDPqlIx3eykUAuBbzvQm8dpfDGL7y0B3DkcCBjJRrWgtbRrTjAvgExWiky+zX7CwhAG6SWXsQ+d1Uq4BzMvKzPSMuAzzNKHL8nuqAGfnIZuzRQ50CNV+XR53bM1uUaumrxk5C6QBJqnsxNMXyiPD4P912bDOa8SfBRJPEesaxaHx2RFyFjHKXfDujnrowYV4kCjWgUEYRu2CgQbMZqxoOoO39wHQ0YkOkzZl/+y3RIYCfZOaKWZo628bj/1Qb48=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
