travis:
  secure:
    BINSTAR_TOKEN: mgJ+CytasLmQ+Up4pxYeRGmHX62maPUr15oT3CnZgwtbaJHY4V/PsLruwMgdZeRor494MdWsLJ25C4pcVSVTnoqXs3t9ZyyGrmnIdcu1tXBWTyfZ2hxcxjb1p0aI42z8VKbq3r3ZYSgul7Nqb2+O9N6zT/IMqFnYP5VU//Nd5V2QGQTke/oM1MSuX4oYES9FE48fYJKq6PlwsviAU/wE2SiF8npjIED1HYJkUCZPSshBONplm0HrXgsfuS1fbmzSrm16LsSUQQHkdhM0lyL8nlvBOwEtMC/2drCtLYwpLYFyfJm/M876gI7ZYaOO1sDwXTrVO4wBELp4ofueo+MykJcjegKTFHZ6HQe2R++aZr8jbmBz0EenGJk0ReS0NRaccVQUssSS47vr5vg2zpaThQ/FaqaIY6cIMvDrAICYWEqeBLta9SQvzr+2Np7KWsD86GdmgrwAyHTNBvbF7Fa+o7NnE8uUwA/I6dDCyKv2zmcGsNlwT7GZH4Dhrj1LKiQw9uYfhE85gc/tYzAQGOuTfcGeddMecwgr/LdpiZe/ZxNJzJ5FT1/O0y27h12+2y5CGR6TvbM7mE1esInD858jrlktI//zYbQ0Skii4NcV9b0fhCO5UYDR1TPqUlKZeYaRgmEFRjspebormaKRNhLQ6FAC4YAuHOC/zBhLw5d1NfA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
